export const SHOW_API_ERROR = 'SHOW_API_ERROR';
export const HIDE_API_ERROR = 'HIDE_API_ERROR';

export const REQUEST_CST_RESULT = 'REQUEST_CST_RESULT';
export const RECEIVE_CST_RESULT = 'RECEIVE_CST_RESULT';

export const REQUEST_IMPROVED_CST_RESULT = 'REQUEST_IMPROVED_CST_RESULT';
export const RECEIVE_IMPROVED_CST_RESULT = 'RECEIVE_IMPROVED_CST_RESULT';

export const REQUEST_ENTITY_RESULT = 'REQUEST_ENTITY_RESULT';
export const RECEIVE_ENTITY_RESULT = 'RECEIVE_ENTITY_RESULT';

export const SET_NL = 'SET_NL';
export const SET_REGEXES = 'SET_REGEXES';

export const HIDE_CST = 'HIDE_CST';
export const SHOW_CST = 'SHOW_CST';

export const HIDE_ENTITIES = 'HIDE_ENTITIES';
export const SHOW_ENTITIES = 'SHOW_ENTITIES';
